apiVersion: external-secrets.io/v1beta1
kind: SecretStore

metadata:
  name: aws-secrets-manager
  namespace: accounts-api

spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-south-1

      auth:
        jwt:
          serviceAccountRef:
            name: accounts-api

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret

metadata:
  name: accounts-api-db-credentials
  namespace: accounts-api

spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore

  target:
    name: accounts-api-db-credentials

  data:
    - secretKey: DB_USER
      remoteRef:
        key: accounts-api/rds
        property: username

    - secretKey: DB_PASSWORD
      remoteRef:
        key: accounts-api/rds
        property: password

