apiVersion: v1
kind: Namespace
metadata:
  name: accounts-api
  labels:
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: "v1.30"
    data-classification: pci-adjacent

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  namespace: accounts-api

spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress-from-alb
  namespace: accounts-api

spec:
  podSelector:
    matchLabels:
      app: accounts-api

  policyTypes:
    - Ingress

  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
      ports:
        - protocol: TCP
          port: 8443

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-egress-accounts-api
  namespace: accounts-api

spec:
  podSelector:
    matchLabels:
      app: accounts-api

  policyTypes:
    - Egress

  egress:
    # PostgreSQL
    - to:
        - ipBlock:
            cidr: 10.0.20.0/24
      ports:
        - protocol: TCP
          port: 5432

    # DNS
    - ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53

    # KYC provider
    #
    # NetworkPolicy does not provide native FQDN-based filtering.
    # HTTPS destination is therefore controlled separately through
    # the egress layer / proxy.
    - ports:
        - protocol: TCP
          port: 443
